import { Restaurant, TodoItem, TouchpointLog } from '../types';

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    name: 'Trattoria Lucca & Wine Bar',
    cuisine: 'Northern Italian & Handmade Pasta',
    address: '412 Bell Street, Suite A, Downtown',
    contact_name: 'Marco Bellini',
    contact_role: 'Executive Chef',
    phone: '(555) 234-8910',
    email: 'marco@trattorialucca.com',
    best_window: 'Morning Prep (9:00 - 11:00 AM)',
    closed_days: ['Monday'],
    status: 'Sample Dropped',
    initial_followup_count: 1, // Historical from CSV
    created_at: '2026-09-12T10:00:00Z',
    notes: 'Looking for a reliable supplier of imported 24-month Parmigiano-Reggiano wheels and artisanal 00 flour. Kitchen prep starts promptly at 8:30 AM.',
    samples_dropped: ['24-Month Parmigiano-Reggiano Wedge', 'Caputo Tipo 00 Flour (10lb)'],
  },
  {
    id: 'rest-2',
    name: 'Ember & Oak Smokehouse',
    cuisine: 'Craft Texas BBQ & Brisket',
    address: '884 Pitmaster Way, Industrial Park',
    contact_name: 'Darius Vance',
    contact_role: 'Owner / Operator',
    phone: '(555) 871-3342',
    email: 'darius@emberandoakbbq.com',
    best_window: 'Between Shifts (2:00 - 4:00 PM)',
    closed_days: ['Monday', 'Tuesday'],
    status: 'Follow-up Due',
    initial_followup_count: 0,
    created_at: '2026-09-18T14:30:00Z',
    notes: 'Burners run from 4 AM. Darius is never available in the morning. Best time is 2:30 PM after the lunch brisket sellout.',
    samples_dropped: ['Prime Black Angus Whole Packer Brisket', 'Hickory Smoked Flake Salt'],
  },
  {
    id: 'rest-3',
    name: "L'Étoile Modern French",
    cuisine: 'Contemporary French Haute Cuisine',
    address: '109 Riverside Promenade',
    contact_name: 'Camille Laurent',
    contact_role: 'Executive Chef',
    phone: '(555) 642-9901',
    email: 'claurent@letoile-dining.com',
    best_window: 'Late Afternoon (3:30 - 5:00 PM)',
    closed_days: ['Sunday', 'Monday'],
    status: 'Tasting / Meeting',
    initial_followup_count: 2,
    created_at: '2026-08-30T11:00:00Z',
    notes: 'Very strict on butter fat percentage (84%+ required) and fresh Périgord truffles. Schedule tasting right before dinner service lineup at 5 PM.',
    samples_dropped: ['Normandy 84% Cultured Butter', 'Winter Black Truffle Puree (200g)'],
  },
  {
    id: 'rest-4',
    name: 'Masa Madre Oaxacan Cantina',
    cuisine: 'Modern Oaxacan & Woodfired Mole',
    address: '320 Mission Blvd, Arts District',
    contact_name: 'Alejandro Morales',
    contact_role: 'Kitchen Manager',
    phone: '(555) 419-7730',
    email: 'alex@masamadrecantina.com',
    best_window: 'Between Shifts (2:00 - 4:00 PM)',
    closed_days: [],
    status: 'Active Customer',
    initial_followup_count: 3,
    created_at: '2026-07-15T09:00:00Z',
    notes: 'Switched to our heirloom blue corn kernels and dried Chilhuacle peppers. Always looking for seasonal citrus and Oaxaca criollo avocados.',
    samples_dropped: ['Heirloom Oaxaca Bolita Blue Corn (50lb)', 'Dried Chilhuacle Negro Peppers'],
  },
  {
    id: 'rest-5',
    name: 'Harbor Mist Seafood Co.',
    cuisine: 'Coastal Raw Bar & Sustainably Caught Finfish',
    address: '5 Pier Street, Harbor District',
    contact_name: 'Sarah Chen',
    contact_role: 'General Manager',
    phone: '(555) 902-1845',
    email: 'schen@harbormistseafood.com',
    best_window: 'Morning Prep (9:00 - 11:00 AM)',
    closed_days: ['Tuesday'],
    status: 'New Lead',
    initial_followup_count: 0,
    created_at: '2026-09-28T09:15:00Z',
    notes: 'New GM hired 2 weeks ago looking to renegotiate seafood distributor contracts. Chef arrives at 9:30 AM to inspect daily dock catch.',
    samples_dropped: [],
  },
  {
    id: 'rest-6',
    name: 'Kuroshio Yakitori & Robata',
    cuisine: 'Japanese Robata Grill & Izakaya',
    address: '77 Lantern Way, Little Tokyo',
    contact_name: 'Kenji Takahashi',
    contact_role: 'Owner / Operator',
    phone: '(555) 338-7261',
    email: 'kenji@kuroshioyakitori.com',
    best_window: 'Late Afternoon (3:30 - 5:00 PM)',
    closed_days: ['Monday'],
    status: 'Sample Dropped',
    initial_followup_count: 1,
    created_at: '2026-09-20T16:00:00Z',
    notes: 'Interested in Kishu Binchotan charcoal and Japanese A5 Wagyu striploin cubes for skewers. Extremely detail-oriented.',
    samples_dropped: ['Miyazaki A5 Wagyu Striploin Strips (2lb)', 'Premium White Binchotan Charcoal'],
  },
  {
    id: 'rest-7',
    name: 'Flour & Hearth Artisan Bakery',
    cuisine: 'Wild Fermentation Sourdough & Viennoiserie',
    address: '1540 Mill Avenue',
    contact_name: 'Elena Rostova',
    contact_role: 'Executive Chef',
    phone: '(555) 512-8844',
    email: 'elena@flourandhearth.com',
    best_window: 'Custom',
    custom_window_start: '11:30',
    custom_window_end: '13:30',
    closed_days: ['Sunday', 'Monday'],
    status: 'Follow-up Due',
    initial_followup_count: 0,
    created_at: '2026-09-05T12:00:00Z',
    notes: 'Bakes overnight (2 AM - 8 AM). Morning is counter rush. She rests between 8 AM and 11 AM, then reviews supplier orders between 11:30 AM - 1:30 PM.',
    samples_dropped: ['Stone-Ground Organic Spelt Flour', 'Valrhona Grand Cru Dark Chocolate Batons'],
  },
  {
    id: 'rest-8',
    name: 'Copper Kettle Farm-to-Table',
    cuisine: 'Organic Regional American & Foraged Greens',
    address: '88 Meadowlands Expressway',
    contact_name: 'Harrison Boyd',
    contact_role: 'Owner / Operator',
    phone: '(555) 779-1120',
    email: 'harrison@copperkettlefarm.com',
    best_window: 'Between Shifts (2:00 - 4:00 PM)',
    closed_days: ['Wednesday'],
    status: 'New Lead',
    initial_followup_count: 0,
    created_at: '2026-09-29T14:00:00Z',
    notes: 'Menu changes bi-weekly based on local purveyors. Need samples of organic grass-fed beef tallow and heirloom root veggies.',
    samples_dropped: [],
  },
  {
    id: 'rest-9',
    name: 'The Gilded Ox Chop House',
    cuisine: 'Dry-Aged Prime Steaks & Classic Cocktails',
    address: '900 Financial Way, 2nd Floor',
    contact_name: 'Julian Sterling',
    contact_role: 'Bar Manager',
    phone: '(555) 304-4590',
    email: 'julian@gildedox.com',
    best_window: 'Late Afternoon (3:30 - 5:00 PM)',
    closed_days: [],
    status: 'Archived / Passed',
    initial_followup_count: 2,
    created_at: '2026-06-10T15:00:00Z',
    notes: 'Locked into multi-year contract with national corporate meat distributor. Bar program was interested in bitters, but kitchen is locked until Q2 2027.',
    samples_dropped: ['Small-batch Artisanal Cocktail Bitters (3pk)'],
  },
];

export const INITIAL_LOGS: TouchpointLog[] = [
  // Trattoria Lucca: initial_followup_count = 1.
  // Log 1: Spoke to Marco (Decision Maker = TRUE) -> Total followups becomes 1 + 1 = 2
  {
    id: 'log-1',
    restaurant_id: 'rest-1',
    date: '2026-09-15T09:45:00Z',
    channel: 'In-Person Drop-in',
    spoke_to_decision_maker: true,
    contact_person: 'Marco Bellini (Executive Chef)',
    notes: 'Dropped by during morning pasta rolling. Handed over 24-month Parmigiano wedge sample. Marco tasted on the spot and praised the crystallization. Requested pricing tier for 2 whole wheels per month.',
  },
  // Log 2: Spoke to Hostess (Decision Maker = FALSE) -> Only increments total attempts!
  {
    id: 'log-2',
    restaurant_id: 'rest-1',
    date: '2026-09-22T10:15:00Z',
    channel: 'In-Person Drop-in',
    spoke_to_decision_maker: false,
    contact_person: 'Gianna (Hostess / Front of House)',
    notes: 'Marco was on an emergency fish delivery call in the walk-in cooler. Dropped updated catalog and spec sheet with Gianna at the host stand. Did not speak directly with Marco.',
  },
  // Log 3: Phone call with Marco (Decision Maker = TRUE)
  {
    id: 'log-3',
    restaurant_id: 'rest-1',
    date: '2026-09-28T09:30:00Z',
    channel: 'Phone Call',
    spoke_to_decision_maker: true,
    contact_person: 'Marco Bellini (Executive Chef)',
    notes: 'Followed up on the Parmigiano test batch. His dinner specials ran through half the wedge in two nights. Scheduled tasting for the 00 Flour next Tuesday.',
  },

  // Ember & Oak Smokehouse
  // Log 4: Missed drop-in (Decision maker = FALSE)
  {
    id: 'log-4',
    restaurant_id: 'rest-2',
    date: '2026-09-21T11:45:00Z',
    channel: 'In-Person Drop-in',
    spoke_to_decision_maker: false,
    contact_person: 'Junior Pit Hand (Kitchen)',
    notes: 'Dropped by too close to lunch rush. Smokehouse line was around the block. Pit crew was frantic slicing brisket. Left my business card with the counter worker. Never visit before 2 PM!',
  },
  // Log 5: Spoke to Darius (Decision maker = TRUE)
  {
    id: 'log-5',
    restaurant_id: 'rest-2',
    date: '2026-09-25T14:45:00Z',
    channel: 'In-Person Drop-in',
    spoke_to_decision_maker: true,
    contact_person: 'Darius Vance (Owner / Pitmaster)',
    notes: 'Caught Darius during 2:45 PM lull while he was wiping down the cutting blocks. Delivered Prime Packer Brisket sample. Discussed weekly volume and consistent fat cap thickness.',
  },

  // L'Étoile Modern French (initial_followup_count = 2)
  // Log 6: Phone call with Camille (Decision maker = TRUE)
  {
    id: 'log-6',
    restaurant_id: 'rest-3',
    date: '2026-09-24T16:15:00Z',
    channel: 'Phone Call',
    spoke_to_decision_maker: true,
    contact_person: 'Camille Laurent (Executive Chef)',
    notes: 'Reviewed tasting notes on the Normandy 84% butter. She noted the lactic acidity is perfect for their laminated brioche. Confirmed in-person tasting appointment for upcoming Thursday at 4 PM.',
  },

  // Masa Madre Oaxacan Cantina (initial = 3)
  // Log 7: SMS with Alex (Decision maker = TRUE)
  {
    id: 'log-7',
    restaurant_id: 'rest-4',
    date: '2026-09-27T15:00:00Z',
    channel: 'SMS / WhatsApp',
    spoke_to_decision_maker: true,
    contact_person: 'Alejandro Morales (Kitchen Manager)',
    notes: 'Texted photos of the new harvest Bolita blue corn batch from Oaxaca. Alex approved the order of 10x 50lb sacks for Friday delivery.',
  },

  // Kuroshio Yakitori
  // Log 8: Left message with Bartender (Decision maker = FALSE)
  {
    id: 'log-8',
    restaurant_id: 'rest-6',
    date: '2026-09-23T15:00:00Z',
    channel: 'In-Person Drop-in',
    spoke_to_decision_maker: false,
    contact_person: 'Taka (Bar Lead)',
    notes: 'Kenji was at the Asian fish market. Left sample package of Binchotan charcoal with the bar lead. Requested callback.',
  },
  // Log 9: Spoke with Kenji (Decision maker = TRUE)
  {
    id: 'log-9',
    restaurant_id: 'rest-6',
    date: '2026-09-29T16:30:00Z',
    channel: 'Phone Call',
    spoke_to_decision_maker: true,
    contact_person: 'Kenji Takahashi (Owner / Operator)',
    notes: 'Kenji tested the Binchotan in their tabletop grill. Heat retention was 4 hours without sparks. Requested sample of Wagyu striploin skewers.',
  },
];

export const INITIAL_TODOS: TodoItem[] = [
  {
    id: 'todo-1',
    restaurant_id: 'rest-1',
    task: 'Deliver 10lb sample bag of Caputo Tipo 00 Flour and price sheet for pasta program',
    owner: 'Me', // Rule 3: 100% Rep-owned
    due_date: '2026-10-02',
    is_completed: false,
    created_at: '2026-09-28T09:35:00Z',
  },
  {
    id: 'todo-2',
    restaurant_id: 'rest-2',
    task: 'Call Darius to confirm brisket yield & discuss standing 6-case weekly delivery schedule',
    owner: 'Me',
    due_date: '2026-10-01', // Today!
    is_completed: false,
    created_at: '2026-09-25T15:00:00Z',
  },
  {
    id: 'todo-3',
    restaurant_id: 'rest-3',
    task: 'Pack 2x fresh Périgord Truffle jars and chilled sample kit for 4 PM kitchen lineup tasting',
    owner: 'Me',
    due_date: '2026-10-02',
    is_completed: false,
    created_at: '2026-09-24T16:20:00Z',
  },
  {
    id: 'todo-4',
    restaurant_id: 'rest-5',
    task: 'Initial drop-in introduction with Sarah Chen; introduce cold-water oysters & halibut program',
    owner: 'Me',
    due_date: '2026-10-03',
    is_completed: false,
    created_at: '2026-09-28T09:30:00Z',
  },
  {
    id: 'todo-5',
    restaurant_id: 'rest-7',
    task: 'Review sourdough flour specs with Elena between 11:30 AM and 1:30 PM (Avoid 8 AM rush)',
    owner: 'Me',
    due_date: '2026-10-05',
    is_completed: false,
    created_at: '2026-09-05T12:10:00Z',
  },
  {
    id: 'todo-6',
    restaurant_id: 'rest-8',
    task: 'Assemble seasonal root vegetable & organic grass-fed tallow presentation packet',
    owner: 'Me',
    due_date: '2026-10-08',
    is_completed: false,
    created_at: '2026-09-29T14:15:00Z',
  },
  {
    id: 'todo-7',
    restaurant_id: 'rest-1',
    task: 'Email initial wholesale pricing tier for 24-month Parmigiano wheels',
    owner: 'Me',
    due_date: '2026-09-18',
    is_completed: true,
    created_at: '2026-09-15T10:00:00Z',
  },
  {
    id: 'todo-8',
    restaurant_id: 'rest-6',
    task: 'Ship tracking confirmation for A5 Wagyu striploin skewer sample pack',
    owner: 'Me',
    due_date: '2026-09-30',
    is_completed: true,
    created_at: '2026-09-29T16:45:00Z',
  },
];
